target 'RC2' do
    pod "Charts"
    pod "FBSDKCoreKit"
    pod "FBSDKLoginKit"
    pod "FBSDKShareKit"
    pod "Firebase/Core"
    pod "Firebase/Database"
    pod "Firebase/Auth"
    
  use_frameworks!
end
